import type { Project } from "./types";

const PDT_PORTRAIT =
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1400&q=80";
const PDT_HERO =
  "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1800&q=80";
const EVENT_HERO =
  "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1800&q=80";
const EVENT_PORTRAIT =
  "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=1400&q=80";

export const SEED_PROJECTS: Project[] = [
  {
    id: "anti-tretas",
    name: "Sessão Anti-Tretas",
    partner: "Para de Tentar",
    type: "booking",
    template: "booking-letter",
    brand: {
      name: "Para de Tentar",
      primary: "#111111",
      accent: "#c4a574",
      background: "#f7f4ee",
      foreground: "#161616",
      muted: "#5d5a54",
      surface: "#fffdf8",
      headingFont: "newsreader",
      bodyFont: "libre-franklin",
      radius: "none",
    },
    photos: {
      hero: PDT_HERO,
      portrait: PDT_PORTRAIT,
      gallery: [],
    },
    form: {
      fields: ["firstName", "email"],
      submitLabel: "Marcar a sessão",
      note: "Gratuita. 30 minutos. Por Google Meet.",
    },
    copy: {
      eyebrow: "Sessão Anti-Tretas · Gratuita · 30 minutos · Google Meet",
      headline: "Há uma coisa importante que continua parada. Vamos perceber porquê.",
      subheadline:
        "Em 30 minutos, clarificamos a mudança que queres fazer, olhamos para aquilo que tem acontecido quando tentas e definimos um próximo passo concreto.",
      cta: "Marcar a sessão",
      ctaHref: "#form",
      ctaSecondary: "Sem obrigação de continuar",
      audience: "Pessoas capazes com uma mudança concreta parada.",
      leadTitle: "Não precisas de estar perdido para ter alguma coisa parada",
      problems: [
        "A conversa que sabes que tens de ter.",
        "Uma decisão à espera do momento certo.",
        "O projeto que começas e deixas cair.",
        "Um hábito que regressa ao ponto de partida.",
        "Algo que dizes querer, mas que continua sem espaço na tua vida.",
      ],
      bodyTitle: "Podes ter uma explicação muito boa e continuar no mesmo sítio",
      body: "Há sempre uma razão plausível. Algumas são verdadeiras. O problema aparece quando todas acabam no mesmo resultado: nada muda. A sessão cria um espaço para olharmos para uma situação concreta sem a maquilhar e sem a transformar num drama maior do que é. Não precisamos de resolver a tua vida. Precisamos de descobrir o que podes fazer a seguir.",
      mechanismTitle: "Uma mudança. Um próximo passo.",
      mechanismSteps: [
        {
          title: "Clarificamos a mudança",
          text: "Percebemos o que queres que seja diferente. Não precisas de chegar com uma resposta perfeita.",
        },
        {
          title: "Olhamos para o que aconteceu",
          text: "O que fizeste, onde paraste, o que tens evitado e que explicação aparece quando chega o momento de agir.",
        },
        {
          title: "Definimos o próximo passo",
          text: "Terminamos com uma ação que faça sentido e que possa realmente acontecer depois da sessão.",
        },
      ],
      offerTitle: "A sessão tem valor por si própria",
      offerName: "Sessão Anti-Tretas",
      offerBullets: [
        "30 minutos para trabalhar uma mudança concreta",
        "Um próximo passo observável, não mais uma intenção",
        "Sem palestra motivacional e sem fórmula universal",
      ],
      bonuses: [],
      proof: [
        {
          quote:
            "Saí com uma ação pequena e vergonhosa de tão concreta. Foi isso que fez a diferença.",
          name: "Cliente da sessão",
          role: "Autorizado para uso interno",
        },
      ],
      guaranteeTitle: "O que podes esperar",
      guarantee:
        "Não te vou prometer que uma conversa resolve tudo. A sessão serve para tornar a situação mais clara e ajudar-te a sair da reflexão para uma ação possível.",
      notFor: [
        "uma palestra motivacional",
        "uma fórmula universal",
        "uma lista genérica de hábitos",
        "pressão para comprar",
      ],
      willGet: [
        "uma situação concreta da tua vida",
        "aquilo que fizeste e evitaste",
        "o ponto onde continuas a parar",
        "uma ação possível depois da sessão",
      ],
      faqs: [
        {
          q: "A sessão é mesmo gratuita?",
          a: "Sim. A Sessão Anti-Tretas dura 30 minutos e não tem qualquer custo.",
        },
        {
          q: "Isto é terapia?",
          a: "Não. A sessão trabalha objetivos, decisões, comportamento e ação. Não diagnostica nem trata problemas de saúde mental.",
        },
        {
          q: "A sessão serve apenas para vender o Vai e Faz?",
          a: "Não. Vais trabalhar uma mudança concreta e sair com um próximo passo. Se o acompanhamento puder ajudar e existir fit, explico. Se não existir, a sessão termina por aí.",
        },
      ],
      nextStep:
        "Escolhes um horário disponível e recebes o acesso ao Google Meet. Traz a mudança, mesmo que ainda esteja mal explicada.",
      legal:
        "A sessão não substitui acompanhamento clínico. Resultados dependem do que fazes depois da conversa.",
    },
    createdAt: "2026-08-22T10:00:00.000Z",
    updatedAt: "2026-08-24T10:00:00.000Z",
  },
  {
    id: "workshop-optin",
    name: "Registo do workshop",
    partner: "Create Pro",
    type: "opt-in",
    template: "opt-in-dense",
    brand: {
      name: "Create Pro",
      primary: "#0b0b0b",
      accent: "#e8c36a",
      background: "#0b0b0b",
      foreground: "#f5f1e8",
      muted: "#b7b1a4",
      surface: "#161616",
      headingFont: "bebas",
      bodyFont: "dm-sans",
      radius: "sm",
    },
    photos: {
      hero: EVENT_HERO,
      portrait: EVENT_PORTRAIT,
      gallery: [],
    },
    form: {
      fields: ["firstName", "lastName", "email", "phone", "business"],
      submitLabel: "Quero o meu lugar",
      note: "Ao submeteres, aceitas ser contactado sobre este evento. Podes sair a qualquer momento.",
    },
    copy: {
      eyebrow: "Workshop ao vivo · 12 de setembro · 19h00 Lisboa",
      headline: "Como um negócio que já vende deixa de recomeçar o funil a cada trimestre.",
      subheadline:
        "90 minutos para escolher uma oferta, um percurso e uma fonte de tráfego. Sem novo branding. Sem mais uma esteira de conteúdos.",
      cta: "Quero o meu lugar",
      ctaHref: "#form",
      audience: "Donos de negócio que já vendem e estão cansados de reconstruir o sistema a cada lançamento.",
      leadTitle: "Isto é para ti se",
      problems: [
        "Já tiveste um lançamento que funcionou e não soubeste repetir.",
        "A equipa produz conteúdo e as vendas continuam a depender de ti.",
        "Tens três ofertas abertas e nenhuma claramente escolhida.",
        "O tráfego existe, mas o percurso até à venda muda todas as semanas.",
        "Cada trimestre parece um negócio novo.",
      ],
      bodyTitle: "O que já vendeu é o ponto de partida",
      body: "A maior parte dos workshops ensina a construir mais peças. Este parte do contrário: olhamos para a venda que já aconteceu, isolamos o que a tornou possível e desenhamos o sistema mais pequeno que a consegue repetir. Sem fórmula secreta. Sem piloto automático.",
      mechanismTitle: "Os 90 minutos",
      mechanismSteps: [
        { title: "A venda que já aconteceu", text: "Isolamos uma oferta que o mercado já pagou." },
        { title: "O percurso único", text: "Um caminho da atenção até ao fecho, sem ramificações." },
        { title: "A fonte que alimenta", text: "Uma origem de tráfego com dono, métrica e cadência." },
      ],
      offerTitle: "O que levas",
      offerName: "Workshop Create Pro",
      offerBullets: [
        "Um mapa de uma página para a tua oferta principal",
        "Critério para recusar o resto",
        "Gravação durante 14 dias",
      ],
      bonuses: ["Folha de diagnóstico comercial", "Checklist de recusa de trabalho"],
      proof: [
        {
          quote: "Pela primeira vez saímos com uma oferta a menos, não com mais um funil.",
          name: "Inês M.",
          role: "Clínica, Lisboa",
        },
        {
          quote: "O critério de recusa valeu mais do que qualquer template.",
          name: "Rui T.",
          role: "Academia, Porto",
        },
      ],
      guaranteeTitle: "Se não te servir",
      guarantee:
        "Se no final dos 90 minutos não tiveres um critério de escolha para a oferta, devolvemos o valor do bilhete.",
      notFor: ["Quem ainda não vendeu", "Quem procura uma fórmula de anúncios"],
      willGet: ["Uma oferta escolhida", "Um percurso desenhado", "Uma fonte nomeada"],
      faqs: [
        {
          q: "É consultoria gratuita?",
          a: "Não. É um workshop com um exercício aplicado ao teu negócio. Não saímos a construir o sistema por ti.",
        },
        {
          q: "Preciso de trazer números?",
          a: "Sim. A última oferta que vendeu, o preço e de onde vieram as pessoas.",
        },
        {
          q: "Fica gravado?",
          a: "Sim, durante 14 dias. O exercício ao vivo não se substitui pela gravação.",
        },
      ],
      nextStep: "Preenches o formulário. Recebes o link do Zoom e a folha de preparação no mesmo dia.",
      legal:
        "Resultados anteriores não são garantia. O workshop não promete faturação nem escala automática.",
    },
    createdAt: "2026-08-20T10:00:00.000Z",
    updatedAt: "2026-08-24T10:00:00.000Z",
  },
  {
    id: "sistema-vendas",
    name: "Sistema de crescimento",
    partner: "REDNA",
    type: "sales",
    template: "sales-long",
    brand: {
      name: "REDNA",
      primary: "#101513",
      accent: "#377fb5",
      background: "#f3f4ee",
      foreground: "#101513",
      muted: "#59615c",
      surface: "#fbfcf8",
      headingFont: "instrument-serif",
      bodyFont: "libre-franklin",
      radius: "none",
    },
    photos: {
      hero: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1800&q=80",
      portrait:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=1400&q=80",
      gallery: [],
    },
    form: {
      fields: ["firstName", "email", "business"],
      submitLabel: "Pedir a conversa",
      note: "A conversa não é consultoria gratuita. Serve para ver se há fit.",
    },
    copy: {
      eyebrow: "Para negócios liderados por especialistas que já vendem",
      headline: "Encontramos o que já faz o teu negócio crescer e construímos um sistema à volta disso.",
      subheadline:
        "Uma oferta. Um funil. Uma fonte de tráfego. Tempo suficiente para melhorar. Sem teatro de agência e sem mais uma esteira de tarefas.",
      cta: "Pedir a conversa",
      ctaHref: "#form",
      ctaSecondary: "Ou continua a improvisar o próximo trimestre",
      audience: "Negócios com vendas reais e um sistema que ainda depende de recomeçar.",
      leadTitle: "Isto é para ti se reconheceres uma destas situações",
      problems: [
        "Já vendeste, mas cada ciclo parece um negócio novo.",
        "Tens marketing a acontecer e dificuldade em dizer o que está a puxar as vendas.",
        "A oferta certa existe e compete com outras três abertas.",
        "O tráfego muda de canal antes de ter tempo para melhorar.",
        "A equipa executa tarefas. Ninguém é dono do percurso até ao fecho.",
        "A faturação sobe e a margem não acompanha.",
      ],
      bodyTitle: "Não precisamos de começar do zero",
      body: "A maior parte das agências chega a vender actividade. Mais páginas, mais conteúdos, mais anúncios. Eu parto do ponto cego: a venda que já aconteceu e o que a está a impedir de se repetir com menos atrito. O trabalho é escolher a alavanca 80/20, recusar o resto e pôr o percurso a funcionar. Não construímos complexidade para justificar trabalho.",
      mechanismTitle: "Como o trabalho acontece",
      mechanismSteps: [
        {
          title: "Diagnosticar",
          text: "Olhamos para o que já vendeu, o que custou, quem fecha e quem opera depois.",
        },
        {
          title: "Escolher",
          text: "Uma oferta, um funil, uma fonte de tráfego. O resto fica de fora por escrito.",
        },
        {
          title: "Construir",
          text: "Os ativos necessários para esse percurso existir, e só esses.",
        },
        {
          title: "Ativar",
          text: "Tráfego, conversa de vendas e cadência com dono.",
        },
        {
          title: "Melhorar",
          text: "Tempo suficiente no mesmo sistema para a margem aparecer nos números, não no relatório.",
        },
      ],
      offerTitle: "O acompanhamento",
      offerName: "Sistema de crescimento",
      offerBullets: [
        "Diagnóstico comercial e escolha da alavanca",
        "Oferta, funil e fonte de tráfego definidos e implementados",
        "Cadência de melhoria durante quatro meses",
        "Garantia de execução: se os ativos acordados não ficarem a funcionar por falha minha, continuo até estarem, sem cobrar mais",
      ],
      bonuses: [],
      proof: [
        {
          quote:
            "Saímos com menos peças do que entrámos. As vendas passaram a ter um sítio óbvio onde melhorar.",
          name: "Cliente de acompanhamento",
          role: "Serviço profissional",
        },
        {
          quote: "O critério não foi faturação. Foi margem e capacidade de operar.",
          name: "Parceiro",
          role: "Negócio com equipa",
        },
      ],
      guaranteeTitle: "Garantia de execução",
      guarantee:
        "Se os ativos acordados não ficarem implementados e a funcionar por falha minha, continuo até estarem, sem cobrar mais. Não é garantia de resultados. É garantia de que o trabalho combinado existe.",
      notFor: [
        "quem procura uma agência 360º",
        "quem quer dinheiro fácil ou piloto automático",
        "quem ainda não tem uma oferta que o mercado já tenha pago",
      ],
      willGet: [
        "um diagnóstico escrito",
        "um percurso comercial escolhido",
        "ativos implementados",
        "uma cadência para melhorar",
      ],
      faqs: [
        {
          q: "Quanto custa?",
          a: "O âmbito está definido. O investimento e o arranque ficam depois da conversa, quando houver fit.",
        },
        {
          q: "Fazes anúncios e conteúdos todos os meses?",
          a: "Não. Isso seria uma esteira. Eu escolho o sistema e ajudo a pô-lo a funcionar. A operação contínua precisa de dono no teu lado.",
        },
        {
          q: "Trabalhas com qualquer negócio?",
          a: "Não. Trabalho com negócios liderados por especialistas que já vendem e têm alguém para operar depois da entrega.",
        },
        {
          q: "A conversa é consultoria gratuita?",
          a: "Não. Serve para perceber se o problema é o certo e se faz sentido trabalhar juntos.",
        },
      ],
      nextStep:
        "Pedimos uma conversa. Se houver fit, avançamos com o diagnóstico e o âmbito já descrito nesta página.",
      legal:
        "REDNA não promete faturação, escala automática nem resultados garantidos. O lucro depende da oferta, do mercado, da execução e de quem opera.",
    },
    createdAt: "2026-08-18T10:00:00.000Z",
    updatedAt: "2026-08-24T10:00:00.000Z",
  },
  {
    id: "workshop-obrigado",
    name: "Obrigado do workshop",
    partner: "Create Pro",
    type: "thanks",
    template: "thanks-next",
    brand: {
      name: "Create Pro",
      primary: "#0b0b0b",
      accent: "#e8c36a",
      background: "#0b0b0b",
      foreground: "#f5f1e8",
      muted: "#b7b1a4",
      surface: "#161616",
      headingFont: "bebas",
      bodyFont: "dm-sans",
      radius: "sm",
    },
    photos: {
      hero: EVENT_HERO,
      portrait: EVENT_PORTRAIT,
      gallery: [],
    },
    form: {
      fields: [],
      submitLabel: "Abrir a folha de preparação",
      note: "",
    },
    copy: {
      eyebrow: "Lugar reservado",
      headline: "Está feito. O próximo passo é hoje, não no dia do workshop.",
      subheadline:
        "Enviámos o link e a folha de preparação para o teu email. Se não aparecer em dois minutos, vê o spam.",
      cta: "Abrir a folha de preparação",
      ctaHref: "#",
      audience: "",
      leadTitle: "",
      problems: [],
      bodyTitle: "",
      body: "",
      mechanismTitle: "",
      mechanismSteps: [],
      offerTitle: "Leva já",
      offerName: "Acesso imediato",
      offerBullets: [
        "Folha de diagnóstico de uma página",
        "Perguntas para trazeres à sessão",
        "Link do Zoom com lembrete 24h antes",
      ],
      bonuses: [],
      proof: [],
      guaranteeTitle: "",
      guarantee: "",
      notFor: [],
      willGet: [],
      faqs: [],
      nextStep: "Preenche a folha antes do workshop. Sem isso, os 90 minutos rendem metade.",
      legal: "Create Pro · Privacidade e termos no rodapé do email de confirmação.",
    },
    createdAt: "2026-08-20T11:00:00.000Z",
    updatedAt: "2026-08-24T10:00:00.000Z",
  },
  {
    id: "redna-conversa",
    name: "Conversa REDNA",
    partner: "REDNA",
    type: "booking",
    template: "booking-editorial",
    brand: {
      name: "REDNA",
      primary: "#101513",
      accent: "#377fb5",
      background: "#f3f4ee",
      foreground: "#101513",
      muted: "#59615c",
      surface: "#fbfcf8",
      headingFont: "instrument-serif",
      bodyFont: "libre-franklin",
      radius: "none",
    },
    photos: {
      hero: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1800&q=80",
      portrait:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=1400&q=80",
      gallery: [],
    },
    form: {
      fields: ["firstName", "email", "business"],
      submitLabel: "Pedir a conversa",
      note: "A conversa não é consultoria gratuita. Serve para ver se há fit.",
    },
    copy: {
      eyebrow: "Conversa · 45 minutos · sem obrigação",
      headline: "Antes de construir mais, percebemos o que está a travar o próximo salto.",
      subheadline:
        "Uma conversa para ver se o problema é o certo e se faz sentido trabalhar juntos. Sem teatro de agência.",
      cta: "Pedir a conversa",
      ctaHref: "#form",
      ctaSecondary: "Não é uma sessão de consultoria gratuita",
      audience: "Negócios liderados por especialistas que já vendem.",
      leadTitle: "Isto serve se reconheceres uma destas situações",
      problems: [
        "Já vendeste e cada ciclo parece um negócio novo.",
        "Há marketing a acontecer e ninguém sabe o que puxa as vendas.",
        "A oferta certa compete com outras três abertas.",
        "O tráfego muda de canal antes de ter tempo para melhorar.",
        "A faturação sobe e a margem não acompanha.",
      ],
      bodyTitle: "Não precisamos de começar do zero",
      body: "A conversa parte do que já vendeu. Isolamos o ponto cego, escolhemos a alavanca e só depois falamos de acompanhamento. Se não houver fit, a conversa termina aí.",
      mechanismTitle: "Os 45 minutos",
      mechanismSteps: [
        { title: "O que já vendeu", text: "Olhamos para a oferta, o preço e de onde vieram as pessoas." },
        { title: "O que trava", text: "Nomeamos o ponto que, resolvido, torna o resto mais fácil." },
        { title: "O próximo passo", text: "Ou há fit e avanço claro, ou a conversa fecha sem pressão." },
      ],
      offerTitle: "A conversa",
      offerName: "Conversa REDNA",
      offerBullets: [
        "Diagnóstico verbal do percurso comercial",
        "Critério para recusar trabalho",
        "Decisão de avançar ou não",
      ],
      bonuses: [],
      proof: [
        {
          quote: "Saímos com menos peças do que entrámos.",
          name: "Cliente",
          role: "Serviço profissional",
        },
      ],
      guaranteeTitle: "O que não é",
      guarantee: "Não é uma auditoria gratuita nem um pitch disfarçado. Se o âmbito não fizer sentido, digo-o.",
      notFor: ["quem procura uma agência 360º", "quem ainda não vendeu"],
      willGet: ["uma leitura do ponto cego", "um próximo passo concreto"],
      faqs: [
        {
          q: "Quanto custa a conversa?",
          a: "A conversa em si não tem preço de entrada. O investimento do acompanhamento fica depois, se houver fit.",
        },
        {
          q: "Preciso de trazer números?",
          a: "Sim. A última oferta que vendeu, o preço e quem opera depois da venda.",
        },
        {
          q: "Vais vender-me o Sistema na hora?",
          a: "Não. Se fizer sentido, explico o âmbito. A decisão fica do teu lado.",
        },
      ],
      nextStep: "Preenches o formulário. Proponho dois horários no mesmo dia.",
      legal: "REDNA não promete resultados. A conversa serve para ver se o problema é o certo.",
    },
    createdAt: "2026-08-24T12:00:00.000Z",
    updatedAt: "2026-08-24T12:00:00.000Z",
  },
  {
    id: "arcano-optin",
    name: "Lista Antes do Arcano",
    partner: "Antes do Arcano",
    type: "opt-in",
    template: "opt-in-light",
    brand: {
      name: "Antes do Arcano",
      primary: "#2b1d16",
      accent: "#8b3d2f",
      background: "#f7f1e8",
      foreground: "#2b1d16",
      muted: "#6d5b50",
      surface: "#fffaf3",
      headingFont: "fraunces",
      bodyFont: "source-serif",
      radius: "none",
    },
    photos: {
      hero: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
      portrait: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
    },
    form: {
      fields: ["firstName", "email"],
      submitLabel: "Quero a carta",
      note: "Uma carta por semana. Podes sair quando quiseres.",
    },
    copy: {
      eyebrow: "Carta semanal",
      headline: "Para quem está cansado de conteúdo que não muda nada na vida real.",
      subheadline:
        "Uma carta curta, uma vez por semana. Sem hábito milagroso. Sem lista de tarefas. Só uma ideia para agir.",
      cta: "Quero a carta",
      ctaHref: "#form",
      audience: "Pessoas que já leram demais e fizeram de menos.",
      leadTitle: "",
      problems: [],
      bodyTitle: "",
      body: "",
      mechanismTitle: "",
      mechanismSteps: [],
      offerTitle: "",
      offerName: "Carta Antes do Arcano",
      offerBullets: [],
      bonuses: [],
      proof: [
        {
          quote: "Pela primeira vez um email que não me pedia mais um hábito.",
          name: "Teresa",
          role: "Leitora",
        },
      ],
      guaranteeTitle: "",
      guarantee: "",
      notFor: [],
      willGet: [],
      faqs: [],
      nextStep: "Recebes a primeira carta no próximo domingo.",
      legal: "Antes do Arcano não vende fórmulas. A carta é o produto.",
    },
    createdAt: "2026-08-24T12:10:00.000Z",
    updatedAt: "2026-08-24T12:10:00.000Z",
  },
  {
    id: "create-manifesto",
    name: "Manifesto Create Pro",
    partner: "Create Pro",
    type: "sales",
    template: "sales-brutal",
    brand: {
      name: "Create Pro",
      primary: "#0b0b0b",
      accent: "#e23c2f",
      background: "#0b0b0b",
      foreground: "#f5f1e8",
      muted: "#b7b1a4",
      surface: "#161616",
      headingFont: "syne",
      bodyFont: "dm-sans",
      radius: "none",
    },
    photos: {
      hero: EVENT_HERO,
      portrait: EVENT_PORTRAIT,
      gallery: [],
    },
    form: {
      fields: ["firstName", "email", "business"],
      submitLabel: "Quero o critério",
      note: "Sem newsletter. Só este passo.",
    },
    copy: {
      eyebrow: "Para quem já vende e ainda reconstruí o sistema",
      headline: "Para de acrescentar peças. Escolhe uma e recusa o resto.",
      subheadline:
        "Um critério escrito para a tua oferta, o teu percurso e a tua fonte de tráfego. Sem novo branding. Sem esteira.",
      cta: "Quero o critério",
      ctaHref: "#form",
      audience: "Donos de negócio com vendas reais e um sistema a mais.",
      leadTitle: "Se isto te soa familiar",
      problems: [
        "Já tiveste um lançamento que funcionou e não soubeste repetir.",
        "A equipa produz e as vendas continuam a depender de ti.",
        "Tens três ofertas abertas e nenhuma escolhida.",
        "Cada trimestre parece um negócio novo.",
      ],
      bodyTitle: "O argumento",
      body: "A maior parte do trabalho de marketing é medo disfarçado de actividade. Este manifesto pede o contrário: uma oferta, um percurso, uma fonte. O resto fica de fora por escrito.",
      mechanismTitle: "Como se escolhe",
      mechanismSteps: [
        { title: "A venda que já aconteceu", text: "Isolamos o que o mercado já pagou." },
        { title: "O percurso único", text: "Um caminho da atenção até ao fecho." },
        { title: "A recusa", text: "O que não vais fazer nos próximos 90 dias." },
      ],
      offerTitle: "O que levas",
      offerName: "Critério Create Pro",
      offerBullets: [
        "Uma página com a oferta escolhida",
        "O percurso desenhado",
        "A lista do que fica de fora",
      ],
      bonuses: [],
      proof: [
        {
          quote: "Pela primeira vez saímos com uma oferta a menos.",
          name: "Inês M.",
          role: "Clínica, Lisboa",
        },
      ],
      guaranteeTitle: "Se não houver critério",
      guarantee: "Se no final não tiveres uma oferta escolhida por escrito, devolvemos o valor.",
      notFor: ["quem ainda não vendeu", "quem quer mais um funil"],
      willGet: ["uma escolha", "uma recusa"],
      faqs: [
        { q: "Isto é um curso?", a: "Não. É um critério. Um documento. Uma decisão." },
        { q: "Ficas a operar o meu negócio?", a: "Não. Tu operas. Eu ajudo a escolher." },
        { q: "Quanto tempo?", a: "Uma sessão. O documento no mesmo dia." },
      ],
      nextStep: "Dizes quem és. Marcamos a sessão de escolha.",
      legal: "Create Pro não promete faturação. Promete um critério.",
    },
    createdAt: "2026-08-24T12:20:00.000Z",
    updatedAt: "2026-08-24T12:20:00.000Z",
  },
];
